#!/usr/bin/python3
import sys

def generate_cmd(brief, enum_str, cmd_str):
    brief=brief.capitalize()
    return f"""/* {brief} command */
CFE_Status_t {cmd_str}(const {cmd_str}_t *Msg)
{{
    CFE_EVS_SendEvent(BPNODE_RESET_INF_EID, CFE_EVS_EventType_INFORMATION, 
                    "{brief} command not implemented");

    return CFE_SUCCESS;
}}
"""

if __name__ == '__main__':
    print (generate_cmd(sys.argv[1], sys.argv[2], sys.argv[3]))
