#!/usr/bin/python3
import sys

def generate_stub(brief, enum_str, cmd_str):
    brief=brief.capitalize()
    return f"""/*
 * ----------------------------------------------------
 * Generated stub function for {cmd_str}()
 * ----------------------------------------------------
 */
CFE_Status_t {cmd_str}(const {cmd_str}_t *Msg)
{{
    UT_GenStub_SetupReturnBuffer({cmd_str}, CFE_Status_t);

    UT_GenStub_AddParam({cmd_str}, const {cmd_str}_t *, Msg);

    UT_GenStub_Execute({cmd_str}, Basic, NULL);

    return UT_GenStub_GetReturnValue({cmd_str}, CFE_Status_t);
}}
"""

if __name__ == '__main__':
    print (generate_stub(sys.argv[1], sys.argv[2], sys.argv[3]))
