#!/usr/bin/python3
import sys

def snake_to_camel(snake_str):
    components = snake_str.split('_')
    return "BPNode_" + ''.join(x.title() for x in components[1:])
    return

if __name__ == '__main__':
    print (snake_to_camel(sys.argv[1]))
