#!/bin/bash
bp-build-err() {
   echo "bp-build exited on error."
   exit 1
}
trap bp-build-err ERR

   cd $CFS_HOME/build
   make DESTDIR=$CFS_HOME/cfs-build-folder -j2 mission-install
   cd $CFS_HOME/cfs-build-folder/exe
   tar -cvf $CFS_HOME/cfs-bpapp.tar .
   cd $CFS_HOME
   ls -l cfs-bpapp.tar
