#!/bin/bash
clean-bp-err() {
   echo "clean-bp exited on error."
   exit 1
}
trap clean-bp-err ERR

   cd $CFS_HOME

   BP_DELETE_LIST=( \
      bpxfer_defs/ build/ host $CFS_REPO/ cfs-bpapp.tar cfs-build-folder exe \
      rx tx tinycbor-source/ tinycbor-staging/
   )

   echo "In $(pwd)"
   echo "Ready to delete:"
   echo ${BP_DELETE_LIST[@]}
   read -p "Delete [y|N]?" choice
   case "${choice}" in
      y|Y ) \
         (set -x; rm -rf ${BP_DELETE_LIST[@]});;
      * ) \
         echo "clean-bp canceled."
    esac

