#!/bin/bash
prep-bp-build-err() {
   echo "prep-bp-build exited on error."
   exit 1
}
trap prep-bp-build-err ERR

   cd $CFS_HOME
   source cfs-env-vars
   git clone https://github.com/nasa/cFS.git "${CFS_REPO}"
   pushd "${CFS_REPO}"
   git submodule init
   git submodule update
   pushd psp
   git fetch --no-tags --depth=1 https://github.com/jphickey/PSP.git \
       techdev-iodriver:techdev-iodriver
   git checkout techdev-iodriver
   popd
   git clone https://github.com/nasa/CF.git apps/cf
   git clone https://github.com/gskenned/bp.git apps/bp
   git clone https://github.com/gskenned/bplib.git libs/bplib
   popd
   mkdir -p ./bpxfer_defs
   cp  "${CFS_REPO}"/cfe/cmake/sample_defs/sample_perfids.h ./bpxfer_defs/cfe_perfids.h
   cp -v -t ./bpxfer_defs "${CFS_REPO}"/cfe/cmake/sample_defs/*{osconfig,custom,options}.cmake
   cp -v -t ./bpxfer_defs "${CFS_REPO}"/apps/bp/.github/buildconfig/*.{cmake,scr}
   cp -rv -t ./bpxfer_defs "${CFS_REPO}"/apps/bp/.github/buildconfig/{tx,rx,tables}
   cmake -DCMAKE_BUILD_TYPE=Release -DSIMULATION=native \
      -DCMAKE_INSTALL_PREFIX=/exe \
      -DMISSIONCONFIG=bpxfer -DMISSION_DEFS=$PWD/bpxfer_defs \
      -B build -S "${CFS_REPO}"/cfe
