#!/bin/bash
prep-bp-build-err() {
   echo "prep-bp-build exited on error."
   exit 1
}
trap prep-bp-build-err ERR

   cd $CFS_HOME
   source cfs-env-vars
   git clone "${CFS_CLONE_URL}" "${CFS_REPO}"
   pushd "${CFS_REPO}"
   git submodule init
   git submodule update
   pushd psp
   git fetch --no-tags --depth=1 "${PSP_CLONE_URL}" \
       techdev-iodriver:techdev-iodriver
   git checkout techdev-iodriver
   popd
   git clone "${CF_CLONE_URL}" apps/cf
   git clone "${BP_CLONE_URL}" "${BP_SOURCE}"
   git clone "${BPLIB_CLONE_URL}" "${BPLIB_SOURCE}"
   popd
   mkdir -p ./bpxfer_defs
   cp  "${CFS_REPO}"/cfe/cmake/sample_defs/sample_perfids.h ./bpxfer_defs/cfe_perfids.h
   cp -v -t ./bpxfer_defs "${CFS_REPO}"/cfe/cmake/sample_defs/*{osconfig,custom,options}.cmake
   cp -v -t ./bpxfer_defs "${CFS_REPO}"/apps/bp/.github/buildconfig/*.{cmake,scr}
   cp -rv -t ./bpxfer_defs "${CFS_REPO}"/apps/bp/.github/buildconfig/{tx,rx,tables}
   cmake -DCMAKE_BUILD_TYPE=Release -DSIMULATION=native \
      -DCMAKE_INSTALL_PREFIX=/exe \
      -DMISSIONCONFIG=bpxfer -DMISSION_DEFS=$PWD/bpxfer_defs \
      -B build -S "${CFS_REPO}"/cfe
